<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MindSDET415" failures="1" tests="1" name="runner.testRunner" time="35.784" errors="0" timestamp="2021-12-29T16:03:54 GMT+05:30" skipped="0">
  <testcase classname="runner.testRunner" name="runScenario" time="35.784">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at uiRepository.uiOperations.modelExtractDetails(uiOperations.java:144)
at stepDefinations.stepDefination.user_must_be_able_to_extract_the_details(stepDefination.java:52)
at âœ½.user must be able to extract the details(file:///C:/Users/sdetjavamind05/.jenkins/amzonTest/src/test/java/features/amazon.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.testRunner -->
